### ISSUE TITLE
Randomise x, y vectors

### ISSUE THREAD

**Issue by brmather** [University-of-Melbourne-Geodynamics/quagmire#1]
Points are randomised in `create_DMPlex_from_points` to improve triangulation performance, but this breaks some existing code in the notebooks. It can be easily fixed, but I'm not sure which is better...

1. Put the permutation routine in the other mesh generation functions, and assume the x,y vectors are shuffled prior to making the DM.
2. Have a convenience method `get_xy` in trimesh to return the shuffled (local) x,y vectors.

The second option might be wiser since refinement will add new points anyway.

**Comment by lmoresi** [comment]
I presume PIXMESH is not affected because it uses the structured DM

So my thought is that we should break the assumption that the points you feed the DM are going to be in any special order in the returned triangulation.

Rewrite notebooks accordingly.

In other words, adopt a common workflow between the massive parallel models and the ones with just a local mesh …  encourage local refinement anyway.

L




On 9 May 2017 at 3:43:54 pm, Ben Mather (notifications@github.com<mailto:notifications@github.com>) wrote:

Points are randomised in create_DMPlex_from_points to improve triangulation performance, but this breaks some existing code in the notebooks. It can be easily fixed, but I'm not sure which is better...

  1.  Put the permutation routine in the other mesh generation functions, and assume the x,y vectors are shuffled prior to making the DM.
  2.  Have a convenience method get_xy in trimesh to return the shuffled (local) x,y vectors.

The second option might be wiser since refinement will add new points anyway.
